package main

import (
    "fmt"
)

const CIPHER = "ULECHAOLEKLSEAEOGEHESFFROOLEOIVORNOHLYLOIADNAHEIKLSNHALNATAIHLRELSVGYOLEOMENUOEETWEDLTYWBSENSHEWTRSIDUIWTNETSSGYIAAYTTHHEKHDDVRNHGARESNNIOTNLIIHYEAGNNAEYECAIRASSLTIOIDLISOOHOAIITROTDOELETFNAHCOGVHIHEMWWDEOIYOUEFDDGUIEGOSLTECNAJSTTNLEATRLDSATESUAMEIEIMHFLGOHUOGHDFODEETEESYBALTYTUONTNOOTYOLITYUOMNEHASYWHAPNRIBYTLRENKOETTAIINWTAHCAOAWSMEALSUDFKEIRYWRLHTTYSLGKLNEOAIAGFLTOFOENSNISHLVTNENEHTSIVHLOSTAHDCAUHASLOEEWTDFHAASYWGDADBSVINHERTOTODTLESDTAUASPOTJFITIOGASTLOBOELAJIENDWEOTUDFKHILALANRHHSOICEYHYEHESAHRIHHRNOCIGTTVOINIHMNEHHATKSOOOAETRKYGHEIIOXCLIAAMWLSALANTSUIAEROITSFLDNOWEUNTLSHOTGFLYTNESMOTTDEZYINSLTEDRALPEHYNOEUASDLTROHNSYLOIRUWBDHOSIYISMACSAHAESHYHONISTHOEIWIEISEOWEOZTWCTUUWTELGTEIWNAIDIRCWOTGENHWLSGUTTYSHTUEOTDGHEKYXYTYHSMSRTORNETLSVNYEIHDFAHOBRNLNOESIOLETLEACLFIAUASSLCOOTHOCTOMDTRTNFTEBNRTOWENIOTESTANHEOLSREEACTOEAYDSBOBFAAODENHWTFMTSMUIALNLHOCVTREVUDTDMNSURSTLTTERDFHONONISTRLTOAETIDLISNUSAHLGKNASLIUOFRDODFAEDERWKTLEDCWEEAUAYMOHHLTAYHSULIRHRFERLEHOHTTEUHEEDENYOUHRIFLWIVERTTHIUHASTBLYIVEHLUBMSLNUTMDIHSUARASSAEERESGMEEIKTOSOAONABEIEAOTOPGNENHHEEFTSOYIAAYELHNHTUHRLHEIOATMSNUX"
const CODEWORD = "secret"

func main() {
    colSize := len(CIPHER) / len(CODEWORD)

    var cols [len(CODEWORD)]string

    for i := 0; i < len(CODEWORD); i++ {
        col := CIPHER[i * colSize:(i + 1) * colSize]
        cols[i] = col
    }

    for i := 0; i < colSize; i++ {
        fmt.Printf("%c", cols[4][i]) // e
        fmt.Printf("%c", cols[1][i]) // e
        fmt.Printf("%c", cols[0][i]) // c
        fmt.Printf("%c", cols[3][i]) // r
        fmt.Printf("%c", cols[2][i]) // s
        fmt.Printf("%c", cols[5][i]) // t
    }
}