package main

import (
    "fmt"
    "sort"
    "strings"
    "bytes"
)

const CIPHER = "ULECHAOLEKLSEAEOGEHESFFROOLEOIVORNOHLYLOIADNAHEIKLSNHALNATAIH" +
    "LRELSVGYOLEOMENUOEETWEDLTYWBSENSHEWTRSIDUIWTNETSSGYIAAYTTHHEKHDDVRNHGARE" +
    "SNNIOTNLIIHYEAGNNAEYECAIRASSLTIOIDLISOOHOAIITROTDOELETFNAHCOGVHIHEMWWDEO" +
    "IYOUEFDDGUIEGOSLTECNAJSTTNLEATRLDSATESUAMEIEIMHFLGOHUOGHDFODEETEESYBALTY" +
    "TUONTNOOTYOLITYUOMNEHASYWHAPNRIBYTLRENKOETTAIINWTAHCAOAWSMEALSUDFKEIRYWR" +
    "LHTTYSLGKLNEOAIAGFLTOFOENSNISHLVTNENEHTSIVHLOSTAHDCAUHASLOEEWTDFHAASYWGD" +
    "ADBSVINHERTOTODTLESDTAUASPOTJFITIOGASTLOBOELAJIENDWEOTUDFKHILALANRHHSOIC" +
    "EYHYEHESAHRIHHRNOCIGTTVOINIHMNEHHATKSOOOAETRKYGHEIIOXCLIAAMWLSALANTSUIAE" +
    "ROITSFLDNOWEUNTLSHOTGFLYTNESMOTTDEZYINSLTEDRALPEHYNOEUASDLTROHNSYLOIRUWB" +
    "DHOSIYISMACSAHAESHYHONISTHOEIWIEISEOWEOZTWCTUUWTELGTEIWNAIDIRCWOTGENHWLS" +
    "GUTTYSHTUEOTDGHEKYXYTYHSMSRTORNETLSVNYEIHDFAHOBRNLNOESIOLETLEACLFIAUASSL" +
    "COOTHOCTOMDTRTNFTEBNRTOWENIOTESTANHEOLSREEACTOEAYDSBOBFAAODENHWTFMTSMUIA" +
    "LNLHOCVTREVUDTDMNSURSTLTTERDFHONONISTRLTOAETIDLISNUSAHLGKNASLIUOFRDODFAE" +
    "DERWKTLEDCWEEAUAYMOHHLTAYHSULIRHRFERLEHOHTTEUHEEDENYOUHRIFLWIVERTTHIUHAS" +
    "TBLYIVEHLUBMSLNUTMDIHSUARASSAEERESGMEEIKTOSOAONABEIEAOTOPGNENHHEEFTSOYIA" +
    "AYELHNHTUHRLHEIOATMSNUX"
const CODEWORD = "secret"

func main() {
    colSize := len(CIPHER) / len(CODEWORD)

    var cols [len(CODEWORD)]string

    s := strings.Split(CODEWORD, "")
    sort.Strings(s)

    for i := 0; i < len(CODEWORD); i++ {
        col := CIPHER[i * colSize:(i + 1) * colSize]
        idx := bytes.IndexRune([]byte(CODEWORD), rune(s[i][0]))
        
        if len(cols[idx]) == 0 {
            cols[idx] = col           
        } else {
            slice := CODEWORD[idx + 1:len(CODEWORD)]
            new_idx := bytes.IndexRune([]byte(slice), rune(s[i][0]))
            idx += new_idx + 1
            cols[idx] = col
        }
    }

    for i := 0; i < colSize; i++ {
        for j := 0; j < len(CODEWORD); j++ {
            fmt.Printf("%c", cols[j][i])
        }
    }
}